### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by KimbelJared** [ebshimizu/discord-mixer-bot#25]
![image](https://user-images.githubusercontent.com/12413407/95289099-d0335c00-081e-11eb-854c-57c8c4317df7.png)

Not really sure what is going on, Im still learning electron

**Comment by ebshimizu** [comment]
hey that looks like an access issue with my fork of [vuex-electron](https://github.com/ebshimizu/vuex-electron). One thing to note is that I'm using yarn as the package manager for this project (I was still on v1 at the time), so you can try using that instead.

**Comment by KimbelJared** [comment]
Hi, i know i am about 2 months late, but finally got around to setting up yarn. Looks like its building with 'yarn build'. Now I need to start the program, I am new to electron, how would i do that? Thanks for all the help

**Comment by KimbelJared** [comment]
Got it all working with yarn :) thank you
